language: java
jdk: openjdk8

branches:
  only:
    - master

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access-key-id: $AWS_ACCESS_KEY
  secret-access-key: $AWS_SECRET_KEY
  region: us-west-2
  app: GameHub
  env: Gamehub-env-1
  bucket_name: gamehub-bucket
  zip_file: './target/gamecheckoutbackend-0.0.1-SNAPSHOT.war'
  on:
    branch: master
