language: java
jdk: openjdk8

branches:
  only:
    - master

before_install:
   - chmod +x mvnw
     # install latest version of node, the default version isnt compatable with the latest angular cli
   - nvm install node

before_script:
  - npm install -g @angular/cli

script:
  - cd GameHub-frontend
  - npm install
  - ng build
  - cd ..
  - mvn install

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access-key-id: $AWS_ACCESS_KEY
  secret-access-key: $AWS_SECRET_KEY
  region: us-west-2
  app: GameHub
  env: Gamehub-env
  bucket_name: gamehub-bucket
  zip_file: './target/gamecheckoutbackend-0.0.1-SNAPSHOT.war'
  on:
    branch: master
